In [4]:
import pandas as pd

df = pd.read_csv('customer_behavior_dataset.csv')
df.head()

,customer_id,age,monthly_income_ghs,monthly_visits,annual_spend_ghs,segment,region,channel,satisfaction_score,returned_item,signup_date
0,C0001,58.0,7843.27,8,5215.66,Home Office,Eastern,Online,2,No,2025-04-15
1,C0002,55.0,4744.39,7,2840.07,Consumer,Eastern,Store,2,Yes,2026-07-29
2,C0003,32.0,3589.95,1,1941.14,Corporate,Ashanti,Online,2,No,2025-12-15
3,C0004,66.0,4720.39,4,2822.80,Consumer,Western,Partner,3,No,2025-09-28
4,C0005,25.0,NaN,10,3942.83,Consumer,Greater Accra,Online,5,No,2026-08-15

In [4]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)
df

,customer_id,age,monthly_income_ghs,monthly_visits,annual_spend_ghs,segment,region,channel,satisfaction_score,returned_item,signup_date
0,C0001,58.0,7843.27,8,5215.66,Home Office,Eastern,Online,2,No,2025-04-15
1,C0002,55.0,4744.39,7,2840.07,Consumer,Eastern,Store,2,Yes,2026-07-29
2,C0003,32.0,3589.95,1,1941.14,Corporate,Ashanti,Online,2,No,2025-12-15
3,C0004,66.0,4720.39,4,2822.80,Consumer,Western,Partner,3,No,2025-09-28
4,C0005,25.0,NaN,10,3942.83,Consumer,Greater Accra,Online,5,No,2026-08-15
5,C0006,60.0,5440.28,3,3480.83,Corporate,Western,Partner,2,Yes,2026-01-25
6,C0007,41.0,6226.43,9,4326.27,Home Office,Ashanti,Online,1,No,2026-07-01
7,C0008,47.0,592.57,8,2917.42,Consumer,Central,Store,3,Yes,2025-08-23
8,C0009,35.0,9446.60,11,6034.39,Home Office,Western,Online,2,No,2026-02-10
9,C0010,34.0,7419.09,9,5311.35,Corporate,Central,Online,5,No,2026-08-21
10,C0011,26.0,4284.78,2,2073.34,Home Office,Western,Partner,1,No,2025-06-13
11,C0012,22.0,3082.23,15,3509.12,Consumer,Greater Accra,Partner,5,No,2026-07-21
12,C0013,52.0,5219.82,11,1658.58,Consumer,Western,Online,1,No,2026-03-22
13,C0014,64.0,6367.29,6,2852.85,Home Office,Eastern,Partner,5,Yes,2025-11-02
14,C0015,30.0,7241.31,1,4663.50,Consumer,Greater Accra,Store,5,No,2026-05-16
15,C0016,NaN,5303.25,3,3345.20,Home Office,Ashanti,Online,1,No,2025-03-12
16,C0017,60.0,2578.82,9,2111.12,Home Office,Ashanti,Partner,5,No,2025-08-05
17,C0018,37.0,2676.04,12,3064.87,Consumer,Ashanti,Online,4,No,2025-05-04
18,C0019,39.0,7845.07,8,4369.35,Consumer,Greater Accra,Online,1,Yes,2025-03-02
19,C0020,39.0,6597.42,16,4630.48,Home Office,Western,Online,2,No,2026-08-08
20,C0021,48.0,5682.44,4,2319.49,Corporate,Western,Partner,4,No,2026-03-10
21,C0022,21.0,2399.60,4,25.00,Consumer,Ashanti,Online,1,No,2025-12-14
22,C0023,30.0,4075.69,6,2226.05,Consumer,Western,Partner,3,No,2025-09-13
23,C0024,24.0,12790.59,1,6970.54,Corporate,Western,Store,1,No,2025-06-20
24,C0025,31.0,8188.71,6,2654.53,Corporate,Western,Store,4,Yes,2026-02-04
25,C0026,45.0,4080.10,16,1743.44,Consumer,Greater Accra,Partner,2,No,2025-10-31
26,C0027,65.0,1835.27,2,582.59,Home Office,Ashanti,Online,1,No,2026-05-30
27,C0028,50.0,6379.54,3,3419.63,Home Office,Ashanti,Partner,2,No,2025-05-03
28,C0029,56.0,6041.66,11,3750.85,Consumer,Central,Store,3,No,2025-11-18
29,C0030,26.0,4362.09,11,2190.76,Home Office,Eastern,Online,1,Yes,2026-04-15
30,C0031,22.0,2775.80,5,1409.85,Corporate,Ashanti,Online,3,Yes,2025-09-08
31,C0032,46.0,6844.68,1,1884.08,Consumer,Central,Online,5,No,2025-04-17
32,C0033,24.0,5141.86,10,2612.24,Consumer,Central,Partner,5,No,2025-12-18
33,C0034,49.0,5167.67,2,4571.40,Consumer,Greater Accra,Store,1,No,2025-10-11
34,C0035,67.0,9193.79,6,6591.13,Consumer,Greater Accra,Online,4,No,2026-07-29
35,C0036,62.0,7371.46,12,3659.86,Consumer,Greater Accra,Store,5,No,2026-03-17
36,C0037,41.0,8215.71,2,2862.48,Home Office,Greater Accra,Store,3,No,2025-09-13
37,C0038,67.0,1219.18,5,262.15,Corporate,Greater Accra,Online,2,No,2025-07-01
38,C0039,65.0,8462.42,14,4240.10,Home Office,Greater Accra,Store,2,No,2025-06-13
39,C0040,20.0,6139.34,15,3514.69,Consumer,Greater Accra,Partner,3,No,2025-08-22
40,C0041,30.0,3836.66,3,2438.74,Corporate,Eastern,Store,3,No,2026-06-06
41,C0042,19.0,9371.65,6,6398.22,Consumer,greater accra,Store,5,No,2025-02-09
42,C0043,40.0,4955.12,4,1753.02,Consumer,Western,Online,4,No,2025-09-18
43,C0044,51.0,7531.03,7,3451.45,Home Office,Central,Partner,3,No,2025-03-13
44,C0045,38.0,4639.03,10,2518.22,Corporate,Western,Partner,5,No,2026-02-23
45,C0046,36.0,3908.70,13,2656.04,Home Office,Greater Accra,Store,2,No,2026-02-20
46,C0047,36.0,6112.64,11,5301.37,Home Office,Ashanti,Partner,4,No,2026-03-29
47,C0048,48.0,6644.90,6,1181.75,Home Office,Eastern,Store,1,No,2026-06-12
48,C0049,23.0,6659.82,10,2406.65,Consumer,Greater Accra,Online,2,No,2025-05-31
49,C0050,48.0,2450.48,15,1331.85,Corporate,Western,Online,4,No,2026-01-29
50,C0051,27.0,5076.75,4,2541.31,Home Office,Eastern,Store,4,No,2025-06-30
51,C0052,21.0,811.17,4,25.00,Home Office,Eastern,Partner,4,No,2026-04-21
52,C0053,-3.0,3754.15,15,4417.90,Corporate,Ashanti,Partner,5,No,2026-07-16
53,C0054,48.0,1865.39,9,2093.84,Corporate,Western,Online,5,No,2025-09-02
54,C0055,63.0,4827.74,11,3845.01,Consumer,Ashanti,Store,5,Yes,2025-05-22
55,C0056,62.0,6035.59,14,4446.06,Corporate,Western,Online,4,No,2026-07-10
56,C0057,31.0,6238.06,1,2073.51,Consumer,Central,Store,5,No,2026-05-04
57,C0058,66.0,1788.96,14,3271.80,Consumer,Central,Store,5,No,2026-05-15
58,C0059,49.0,7069.34,13,4442.16,Home Office,Eastern,Online,2,No,2025-05-11
59,C0060,43.0,2604.79,3,662.36,Consumer,Greater Accra,Store,4,No,2026-04-18
60,C0061,42.0,4119.71,11,3713.94,Corporate,Greater Accra,Store,4,No,2026-03-08
61,C0062,19.0,5195.79,12,3047.38,Consumer,Ashanti,Online,2,Yes,2025-02-11
62,C0063,19.0,4078.77,16,2711.06,Home Office,Central,Store,1,No,2026-04-22
63,C0064,28.0,944.88,4,99999.00,Home Office,Greater Accra,Store,2,No,2025-04-21
64,C0065,54.0,2867.65,13,246.91,Consumer,Central,Partner,2,Yes,2025-09-06
65,C0066,56.0,6480.50,2,1493.82,Consumer,Eastern,Partner,3,No,2026-01-15
66,C0067,39.0,7385.20,16,4762.09,Home Office,Western,Partner,1,No,2026-01-06
67,C0068,27.0,2060.26,9,2301.61,Corporate,Eastern,Store,5,No,2026-04-22
68,C0069,38.0,7560.85,3,2220.19,Corporate,Eastern,Partner,3,No,2025-09-07
69,C0070,60.0,4832.78,11,3267.75,Corporate,Central,Store,2,No,2025-08-06
70,C0071,35.0,7583.87,9,3169.11,Consumer,Greater Accra,Online,5,Yes,2026-06-14
71,C0072,64.0,2975.83,8,2689.80,Consumer,Greater Accra,Store,4,No,2026-04-04
72,C0073,32.0,3906.37,12,3178.80,Home Office,Eastern,Store,4,No,2026-03-12
73,C0074,40.0,4712.69,9,2163.41,Corporate,Greater Accra,Partner,2,Yes,2025-07-17
74,C0075,52.0,8262.82,7,3871.50,Home Office,Eastern,Partner,9,No,2025-10-11
75,C0076,56.0,5001.01,7,3273.39,Consumer,Central,Online,3,No,2026-01-05
76,C0077,63.0,3556.87,2,1608.68,Home Office,Western,Online,5,No,2025-05-10
77,C0078,18.0,3087.18,15,2184.28,Corporate,Western,Online,3,No,2025-02-22
78,C0079,22.0,4531.27,2,2426.82,Corporate,Greater Accra,Online,2,No,2026-07-31
79,C0080,25.0,3164.78,8,1752.46,Corporate,Central,Partner,5,No,2026-04-07
80,C0081,45.0,4202.48,4,3475.20,Home Office,Greater Accra,Online,2,No,2025-09-28
81,C0082,33.0,5582.13,1,2930.07,Corporate,Greater Accra,Online,4,No,2026-04-27
82,C0083,36.0,4325.77,15,1795.12,Home Office,Eastern,Partner,1,No,2025-09-28
83,C0084,30.0,2852.22,5,2248.49,Consumer,Ashanti,Store,3,No,2025-03-15
84,C0085,56.0,5182.15,10,1949.09,Home Office,Central,Partner,4,Yes,2026-04-25
85,C0086,43.0,7515.49,16,4347.49,Corporate,Central,Partner,4,Yes,2099-01-01
86,C0087,34.0,6694.29,1,3208.27,Corporate,Eastern,Partner,3,Yes,2025-06-29
87,C0088,46.0,6348.50,14,3744.27,Corporate,Western,Store,4,Yes,2026-04-27
88,C0089,38.0,3205.11,11,732.48,Home Office,Western,Partner,4,No,2025-10-23
89,C0090,20.0,3448.00,11,2717.80,Consumer,Eastern,Store,1,No,2026-06-11
90,C0091,44.0,7592.88,16,5160.41,Corporate,Eastern,Online,4,Yes,2025-07-28
91,C0092,36.0,2191.85,4,1883.84,Corporate,Eastern,Online,1,No,2025-06-12
92,C0093,53.0,3945.22,4,2485.72,Corporate,Central,Partner,4,Yes,2025-06-07
93,C0094,63.0,4615.65,16,5220.12,Consumer,Western,Online,2,No,2026-07-19
94,C0095,56.0,887.07,3,553.07,Home Office,Central,Online,3,No,2025-12-15
95,C0096,36.0,4599.89,16,1639.46,Corporate,Central,Store,2,No,2026-07-06
96,C0097,53.0,5365.12,11,2427.80,Corporate,Ashanti,Store,2,No,2026-08-09
97,C0098,20.0,4212.71,13,3978.80,Consumer,Ashanti,Partner,4,No,2026-05-23
98,C0099,55.0,4724.13,15,3781.07,Home Office,Ashanti,Store,1,No,2025-01-16
99,C0100,59.0,6013.53,9,3400.78,Corporate,Eastern,Store,3,No,2025-03-24
100,C0101,38.0,2131.64,16,899.43,Consumer,Central,Online,5,Yes,2025-03-12
101,C0102,65.0,10101.28,4,6300.11,Consumer,Greater Accra,Store,4,No,2025-11-03
102,C0103,21.0,4652.19,5,3405.33,Home Office,Ashanti,Online,2,No,2026-08-03
103,C0104,29.0,8936.40,8,5616.40,Corporate,Central,Store,4,No,2025-08-26
104,C0105,34.0,2956.31,15,842.86,Corporate,Central,Partner,3,No,2025-03-17
105,C0106,37.0,3781.98,9,1701.91,Corporate,Western,Online,4,No,2025-07-23
106,C0107,33.0,3744.79,10,3142.81,Corporate,Greater Accra,Partner,3,Yes,2026-02-10
107,C0108,61.0,6201.86,16,1629.95,Consumer,Ashanti,Partner,3,No,2025-12-27
108,C0109,34.0,3728.96,5,738.90,Corporate,Greater Accra,Partner,1,Yes,2025-11-13
109,C0110,41.0,5099.04,10,2734.19,Consumer,Ashanti,Partner,3,No,2025-06-29
110,C0111,41.0,640.89,6,393.51,Home Office,Central,Online,3,No,2025-10-30
111,C0112,47.0,6325.43,8,3405.54,Corporate,Greater Accra,Store,4,No,2025-04-03
112,C0113,52.0,6636.54,9,4389.88,Consumer,Ashanti,Store,5,No,2026-01-16
113,C0114,19.0,1524.08,11,68.14,Home Office,Western,Partner,5,No,2025-03-06
114,C0115,37.0,4581.11,2,1849.99,Consumer,Greater Accra,Online,1,No,2026-05-20
115,C0116,52.0,6719.74,14,5000.29,Home Office,Greater Accra,Store,5,No,2026-03-01
116,C0117,57.0,870.68,2,1837.48,Corporate,Ashanti,Store,3,No,2026-03-31
117,C0118,24.0,7195.05,12,4149.10,Consumer,Greater Accra,Store,1,No,2025-10-10
118,C0119,23.0,3632.25,1,557.77,Consumer,Eastern,Online,1,No,2025-09-07
119,C0120,22.0,6483.32,7,2453.61,Home Office,Greater Accra,Store,2,No,2025-06-01
120,C0121,27.0,7809.81,6,3931.70,Consumer,Central,Online,1,Yes,2025-05-15
121,C0122,55.0,4619.00,2,2774.38,Consumer,Greater Accra,Store,2,No,2026-06-23
122,C0123,46.0,5641.32,4,1756.23,Home Office,Eastern,Store,4,No,2025-02-14
123,C0124,47.0,4871.86,16,3365.03,Corporate,Western,Online,4,No,2025-04-21
124,C0125,23.0,4679.07,5,3014.60,Home Office,Eastern,Store,3,No,2026-01-26
125,C0126,47.0,2974.03,4,1643.18,Corporate,Ashanti,Store,5,No,2026-03-17
126,C0127,39.0,6190.23,4,2278.52,Home Office,Central,Store,3,No,2025-11-17
127,C0128,27.0,4279.31,3,1187.17,Consumer,Central,Online,1,Yes,2026-03-19
128,C0129,53.0,10091.59,11,6352.04,Home Office,Western,Partner,1,No,2025-12-29
129,C0130,21.0,7988.53,12,4361.02,Home Office,Western,Online,1,No,2025-06-08
130,C0131,24.0,3624.93,4,2950.46,Home Office,Eastern,Partner,3,No,2026-03-16
131,C0132,61.0,4897.60,9,2797.73,Home Office,Central,Store,1,No,2025-10-07
132,C0133,40.0,9437.80,13,5425.59,Consumer,Eastern,Online,1,No,2025-02-01
133,C0134,42.0,3520.65,12,3022.99,Home Office,Greater Accra,Online,3,No,2026-08-05
134,C0135,27.0,6800.54,3,4416.15,Corporate,Eastern,Store,3,No,2026-03-11
135,C0136,44.0,4689.17,4,4026.48,Corporate,Eastern,Store,3,No,2025-04-24
136,C0137,51.0,4881.48,13,3050.40,Consumer,Central,Online,5,Yes,2025-01-08
137,C0138,67.0,6249.75,11,4301.54,Home Office,Western,Online,1,Yes,2026-05-25
138,C0139,26.0,2809.48,12,3297.14,Corporate,Greater Accra,Store,1,No,2025-02-13
139,C0140,22.0,6980.88,13,3298.42,Corporate,Greater Accra,Store,4,No,2025-04-28
140,C0141,28.0,6123.43,12,2525.30,Consumer,Western,Partner,1,No,2025-04-19
141,C0142,43.0,3115.89,10,2109.12,Consumer,Greater Accra,Partner,3,No,2025-12-08
142,C0143,58.0,7091.51,12,4956.31,Consumer,Ashanti,Store,3,No,2025-08-30
143,C0144,30.0,5759.31,3,3331.90,Home Office,Eastern,Store,2,No,2026-04-21
144,C0145,61.0,7606.00,11,3795.81,Consumer,Western,Store,3,No,2026-03-27
145,C0146,58.0,4651.65,2,2983.04,Corporate,Western,Online,3,Yes,2025-11-14
146,C0147,21.0,4027.42,3,2641.27,Home Office,Eastern,Partner,5,No,2026-04-19
147,C0148,20.0,1563.14,7,1836.03,Consumer,Greater Accra,Store,3,No,2026-05-29
148,C0149,24.0,6696.00,3,1588.78,Consumer,Western,Store,5,No,2025-02-10
149,C0150,51.0,3977.83,12,2730.46,Corporate,Eastern,Online,3,No,2026-02-23
150,C0151,58.0,4733.62,4,2189.84,Corporate,Eastern,Online,5,No,2025-10-18
151,C0152,39.0,7902.24,12,5263.15,Home Office,Greater Accra,Store,3,No,2025-05-13
152,C0153,53.0,2542.28,5,2746.22,Home Office,Central,Online,5,Yes,2026-03-10
153,C0154,41.0,3334.52,11,4612.19,Consumer,Ashanti,Online,4,No,2025-08-20
154,C0155,36.0,5742.21,2,2390.26,Consumer,Ashanti,Online,3,No,2026-01-21
155,C0156,62.0,5705.09,6,1363.71,Corporate,Ashanti,Store,4,Yes,2026-02-25
156,C0157,57.0,4440.36,15,4813.82,Corporate,Ashanti,Store,2,No,2025-11-13
157,C0158,61.0,10928.26,15,5298.76,Home Office,Western,Online,3,No,2026-05-30
158,C0159,30.0,5562.82,9,2776.40,Home Office,Greater Accra,Partner,1,No,2026-01-16
159,C0160,51.0,6221.37,6,2683.36,Consumer,Western,Online,3,No,2026-06-10
160,C0161,32.0,6976.07,1,1420.75,Home Office,Central,Online,4,Yes,2026-02-10
161,C0162,42.0,7234.53,1,3308.87,Consumer,Ashanti,Online,3,Yes,2025-12-10
162,C0163,36.0,7262.22,5,3160.07,Consumer,Greater Accra,Store,4,No,2025-01-06
163,C0164,31.0,6548.14,14,3104.88,Corporate,Greater Accra,Online,1,No,2025-09-01
164,C0165,33.0,1931.32,15,2959.12,Home Office,Eastern,Online,1,Yes,2026-05-27
165,C0166,58.0,3644.26,5,1996.71,Home Office,Central,Online,3,No,2025-01-02
166,C0167,54.0,2513.60,3,2088.77,Home Office,Eastern,Partner,5,No,2025-03-11
167,C0168,50.0,3230.23,16,2498.15,Corporate,Greater Accra,Store,1,No,2026-01-18
168,C0169,22.0,3285.41,4,3096.30,Consumer,Central,Partner,5,No,2025-05-17
169,C0170,39.0,5706.24,15,3299.69,Consumer,Western,Online,4,No,2025-05-19
170,C0171,36.0,6313.04,2,4614.92,Corporate,Eastern,Store,3,No,2026-06-12
171,C0172,34.0,8150.27,10,4830.25,Corporate,Greater Accra,Store,3,Yes,2025-12-06
172,C0173,45.0,7861.35,13,3640.06,Home Office,Western,Store,3,No,2026-05-24
173,C0174,51.0,5108.55,14,3881.18,Home Office,Central,Store,1,No,2025-07-04
174,C0175,24.0,7905.85,10,5081.26,Home Office,Western,Store,4,No,2025-06-20
175,C0176,46.0,9292.98,12,5706.57,Home Office,Greater Accra,Online,5,No,2025-10-09
176,C0177,60.0,3904.15,6,1580.38,Consumer,Ashanti,Online,1,No,2026-03-25
177,C0178,33.0,5557.48,13,2712.93,Home Office,Western,Store,5,Yes,2025-06-07
178,C0179,41.0,4411.56,5,2541.30,Corporate,Central,Online,5,No,2026-02-12
179,C0180,25.0,6529.63,13,4142.14,Corporate,Western,Online,5,Yes,2025-09-26
180,C0181,57.0,4162.67,16,5297.42,Consumer,Western,Online,2,Yes,2025-05-19
181,C0182,63.0,4352.77,11,3031.43,Home Office,Central,Store,3,Yes,2026-07-18
182,C0183,28.0,4057.14,6,222.67,Consumer,Ashanti,Online,3,No,2025-05-05
183,C0184,49.0,7832.40,12,4743.05,Consumer,Central,Store,4,No,2025-03-30
184,C0185,63.0,4701.50,14,2167.47,Corporate,Greater Accra,Store,5,Yes,2025-05-09
185,C0186,47.0,4379.39,6,1690.42,Consumer,Greater Accra,Partner,2,No,2026-05-30
186,C0187,27.0,4783.59,8,3365.02,Corporate,Ashanti,Partner,3,No,2025-03-22
187,C0188,53.0,4749.90,3,3707.39,Consumer,Ashanti,Partner,5,No,2026-08-18
188,C0189,57.0,4674.75,2,1000.54,Home Office,Eastern,Store,1,Yes,2025-02-16
189,C0190,59.0,5867.04,1,3925.71,Corporate,Ashanti,Partner,4,No,2025-11-06
190,C0191,43.0,4959.95,2,2755.50,Corporate,Western,Online,2,No,2026-03-02
191,C0192,39.0,3775.04,11,2122.89,Corporate,Eastern,Partner,3,No,2025-05-14
192,C0193,24.0,4209.58,9,3625.35,Consumer,Greater Accra,Store,4,No,2025-05-25
193,C0194,42.0,6636.63,6,2751.46,Consumer,Western,Partner,3,No,2025-07-14
194,C0195,47.0,3396.13,1,1619.62,Corporate,Ashanti,Online,1,No,2026-06-02
195,C0196,55.0,4792.57,16,3760.87,Home Office,Greater Accra,Online,5,No,2025-10-20
196,C0197,45.0,6296.74,12,4408.76,Corporate,Greater Accra,Partner,4,No,2025-02-16
197,C0198,53.0,6108.42,3,4137.54,Corporate,Eastern,Partner,4,No,2026-07-18
198,C0199,57.0,9388.99,13,7083.13,Corporate,Ashanti,Online,3,No,2026-07-26
199,C0200,56.0,2731.22,2,1334.96,Corporate,Eastern,Store,1,No,2025-12-08
200,C0201,27.0,3214.73,11,1673.53,Corporate,Eastern,Partner,5,No,2025-06-16
201,C0202,37.0,3122.18,16,2137.13,Consumer,Central,Store,5,No,2026-05-02
202,C0203,61.0,6883.10,10,4574.10,Home Office,Eastern,Partner,1,No,2025-09-29
203,C0204,32.0,4703.21,6,1389.30,Home Office,Ashanti,Online,5,No,2025-06-01
204,C0205,54.0,6160.12,1,2710.49,Consumer,Western,Partner,4,No,2026-03-05
205,C0206,31.0,2133.00,16,3195.75,Consumer,Eastern,Store,1,No,2026-06-16
206,C0207,60.0,3176.47,6,2064.59,Corporate,Central,Partner,4,No,2026-07-14
207,C0208,48.0,5760.69,10,4110.57,Home Office,Ashanti,Partner,2,No,2025-10-23
208,C0209,63.0,2804.83,9,2102.16,Home Office,Eastern,Store,3,Yes,2026-08-11
209,C0210,43.0,7375.37,5,1596.03,Home Office,Greater Accra,Store,3,Yes,2025-10-22
210,C0211,46.0,3259.70,7,753.17,Home Office,Central,Online,2,No,2026-07-30
211,C0212,24.0,3113.47,8,1241.73,Consumer,Greater Accra,Store,1,No,2025-08-27
212,C0213,39.0,5003.11,5,2248.22,Home Office,Western,Store,1,No,2026-02-21
213,C0214,59.0,6890.24,11,6361.82,Home Office,Eastern,Online,3,Yes,2025-04-02
214,C0215,52.0,4909.30,2,532.29,Consumer,Western,Store,2,No,2025-06-30
215,C0216,29.0,10152.78,10,4475.95,Home Office,Eastern,Online,1,Yes,2025-11-02
216,C0217,39.0,3839.78,16,5876.82,Consumer,Greater Accra,Store,2,No,2025-10-07
217,C0218,28.0,4840.70,6,1324.61,Home Office,Ashanti,Online,1,No,2025-10-30
218,C0219,57.0,7969.96,14,3184.83,Corporate,Greater Accra,Online,5,No,2025-03-30
219,C0220,26.0,327.81,1,546.85,Corporate,Central,Store,3,No,2025-08-30
220,C0221,37.0,2820.34,9,1420.47,Home Office,Greater Accra,Store,3,No,2025-03-05
221,C0222,37.0,6917.67,10,5182.57,Home Office,Ashanti,Online,1,No,2026-01-12
222,C0223,26.0,2908.02,12,2471.64,Home Office,Ashanti,Online,4,No,2026-07-05
223,C0224,61.0,5327.06,3,722.58,Home Office,Central,Online,5,No,2026-06-25
224,C0225,54.0,8204.70,7,5443.75,Corporate,Eastern,Store,5,No,2025-06-18
225,C0226,25.0,3785.07,16,1696.45,Corporate,Ashanti,Partner,1,No,2025-02-26
226,C0227,44.0,4502.27,15,3388.87,Corporate,Greater Accra,Partner,3,Yes,2026-02-10
227,C0228,31.0,4636.49,12,2969.78,Corporate,Greater Accra,Store,1,Yes,2025-03-12
228,C0229,44.0,5682.49,14,4210.83,Corporate,Western,Online,3,No,2026-04-05
229,C0230,61.0,9370.80,5,4209.45,Home Office,Western,Partner,3,Yes,2025-07-02
230,C0231,26.0,4993.29,1,1664.17,Home Office,Eastern,Store,1,No,2026-04-20
231,C0232,52.0,4098.86,15,3591.55,Consumer,Greater Accra,Online,3,No,2025-10-10
232,C0233,60.0,2071.56,1,1804.06,Consumer,Eastern,Online,2,No,2025-03-10
233,C0234,46.0,2525.11,2,452.61,Corporate,Ashanti,Partner,2,Yes,2026-02-16
234,C0235,31.0,5300.10,5,1167.20,Home Office,Eastern,Store,5,No,2025-08-28
235,C0236,54.0,2637.48,11,1302.59,Home Office,Eastern,Online,2,No,2025-05-27
236,C0237,44.0,4967.61,6,3065.54,Corporate,Western,Partner,4,No,2025-02-18
237,C0238,38.0,4487.97,10,1951.27,Corporate,Ashanti,Online,4,No,2026-07-05
238,C0239,37.0,5933.40,15,3531.13,Home Office,Eastern,Online,1,No,2026-03-03
239,C0240,42.0,5263.52,3,3263.50,Home Office,Ashanti,Online,4,No,2025-04-05
240,C0101,38.0,2131.64,16,899.43,Consumer,Central,Online,5,Yes,2025-03-12
241,C0102,65.0,10101.28,4,6300.11,Consumer,Greater Accra,Store,4,No,2025-11-03

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         242 non-null    str
 1   age                 241 non-null    float64
 2   monthly_income_ghs  241 non-null    float64
 3   monthly_visits      242 non-null    int64
 4   annual_spend_ghs    242 non-null    float64
 5   segment             242 non-null    str
 6   region              242 non-null    str
 7   channel             242 non-null    str
 8   satisfaction_score  242 non-null    int64
 9   returned_item       242 non-null    str
 10  signup_date         242 non-null    str
dtypes: float64(3), int64(2), str(6)
memory usage: 20.9 KB

In [6]:
df.isnull()

,customer_id,age,monthly_income_ghs,monthly_visits,annual_spend_ghs,segment,region,channel,satisfaction_score,returned_item,signup_date
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False
15,False,True,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False,False,False
50,False,False,False,False,False,False,False,False,False,False,False
51,False,False,False,False,False,False,False,False,False,False,False
52,False,False,False,False,False,False,False,False,False,False,False
53,False,False,False,False,False,False,False,False,False,False,False
54,False,False,False,False,False,False,False,False,False,False,False
55,False,False,False,False,False,False,False,False,False,False,False
56,False,False,False,False,False,False,False,False,False,False,False
57,False,False,False,False,False,False,False,False,False,False,False
58,False,False,False,False,False,False,False,False,False,False,False
59,False,False,False,False,False,False,False,False,False,False,False
60,False,False,False,False,False,False,False,False,False,False,False
61,False,False,False,False,False,False,False,False,False,False,False
62,False,False,False,False,False,False,False,False,False,False,False
63,False,False,False,False,False,False,False,False,False,False,False
64,False,False,False,False,False,False,False,False,False,False,False
65,False,False,False,False,False,False,False,False,False,False,False
66,False,False,False,False,False,False,False,False,False,False,False
67,False,False,False,False,False,False,False,False,False,False,False
68,False,False,False,False,False,False,False,False,False,False,False
69,False,False,False,False,False,False,False,False,False,False,False
70,False,False,False,False,False,False,False,False,False,False,False
71,False,False,False,False,False,False,False,False,False,False,False
72,False,False,False,False,False,False,False,False,False,False,False
73,False,False,False,False,False,False,False,False,False,False,False
74,False,False,False,False,False,False,False,False,False,False,False
75,False,False,False,False,False,False,False,False,False,False,False
76,False,False,False,False,False,False,False,False,False,False,False
77,False,False,False,False,False,False,False,False,False,False,False
78,False,False,False,False,False,False,False,False,False,False,False
79,False,False,False,False,False,False,False,False,False,False,False
80,False,False,False,False,False,False,False,False,False,False,False
81,False,False,False,False,False,False,False,False,False,False,False
82,False,False,False,False,False,False,False,False,False,False,False
83,False,False,False,False,False,False,False,False,False,False,False
84,False,False,False,False,False,False,False,False,False,False,False
85,False,False,False,False,False,False,False,False,False,False,False
86,False,False,False,False,False,False,False,False,False,False,False
87,False,False,False,False,False,False,False,False,False,False,False
88,False,False,False,False,False,False,False,False,False,False,False
89,False,False,False,False,False,False,False,False,False,False,False
90,False,False,False,False,False,False,False,False,False,False,False
91,False,False,False,False,False,False,False,False,False,False,False
92,False,False,False,False,False,False,False,False,False,False,False
93,False,False,False,False,False,False,False,False,False,False,False
94,False,False,False,False,False,False,False,False,False,False,False
95,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False
100,False,False,False,False,False,False,False,False,False,False,False
101,False,False,False,False,False,False,False,False,False,False,False
102,False,False,False,False,False,False,False,False,False,False,False
103,False,False,False,False,False,False,False,False,False,False,False
104,False,False,False,False,False,False,False,False,False,False,False
105,False,False,False,False,False,False,False,False,False,False,False
106,False,False,False,False,False,False,False,False,False,False,False
107,False,False,False,False,False,False,False,False,False,False,False
108,False,False,False,False,False,False,False,False,False,False,False
109,False,False,False,False,False,False,False,False,False,False,False
110,False,False,False,False,False,False,False,False,False,False,False
111,False,False,False,False,False,False,False,False,False,False,False
112,False,False,False,False,False,False,False,False,False,False,False
113,False,False,False,False,False,False,False,False,False,False,False
114,False,False,False,False,False,False,False,False,False,False,False
115,False,False,False,False,False,False,False,False,False,False,False
116,False,False,False,False,False,False,False,False,False,False,False
117,False,False,False,False,False,False,False,False,False,False,False
118,False,False,False,False,False,False,False,False,False,False,False
119,False,False,False,False,False,False,False,False,False,False,False
120,False,False,False,False,False,False,False,False,False,False,False
121,False,False,False,False,False,False,False,False,False,False,False
122,False,False,False,False,False,False,False,False,False,False,False
123,False,False,False,False,False,False,False,False,False,False,False
124,False,False,False,False,False,False,False,False,False,False,False
125,False,False,False,False,False,False,False,False,False,False,False
126,False,False,False,False,False,False,False,False,False,False,False
127,False,False,False,False,False,False,False,False,False,False,False
128,False,False,False,False,False,False,False,False,False,False,False
129,False,False,False,False,False,False,False,False,False,False,False
130,False,False,False,False,False,False,False,False,False,False,False
131,False,False,False,False,False,False,False,False,False,False,False
132,False,False,False,False,False,False,False,False,False,False,False
133,False,False,False,False,False,False,False,False,False,False,False
134,False,False,False,False,False,False,False,False,False,False,False
135,False,False,False,False,False,False,False,False,False,False,False
136,False,False,False,False,False,False,False,False,False,False,False
137,False,False,False,False,False,False,False,False,False,False,False
138,False,False,False,False,False,False,False,False,False,False,False
139,False,False,False,False,False,False,False,False,False,False,False
140,False,False,False,False,False,False,False,False,False,False,False
141,False,False,False,False,False,False,False,False,False,False,False
142,False,False,False,False,False,False,False,False,False,False,False
143,False,False,False,False,False,False,False,False,False,False,False
144,False,False,False,False,False,False,False,False,False,False,False
145,False,False,False,False,False,False,False,False,False,False,False
146,False,False,False,False,False,False,False,False,False,False,False
147,False,False,False,False,False,False,False,False,False,False,False
148,False,False,False,False,False,False,False,False,False,False,False
149,False,False,False,False,False,False,False,False,False,False,False
150,False,False,False,False,False,False,False,False,False,False,False
151,False,False,False,False,False,False,False,False,False,False,False
152,False,False,False,False,False,False,False,False,False,False,False
153,False,False,False,False,False,False,False,False,False,False,False
154,False,False,False,False,False,False,False,False,False,False,False
155,False,False,False,False,False,False,False,False,False,False,False
156,False,False,False,False,False,False,False,False,False,False,False
157,False,False,False,False,False,False,False,False,False,False,False
158,False,False,False,False,False,False,False,False,False,False,False
159,False,False,False,False,False,False,False,False,False,False,False
160,False,False,False,False,False,False,False,False,False,False,False
161,False,False,False,False,False,False,False,False,False,False,False
162,False,False,False,False,False,False,False,False,False,False,False
163,False,False,False,False,False,False,False,False,False,False,False
164,False,False,False,False,False,False,False,False,False,False,False
165,False,False,False,False,False,False,False,False,False,False,False
166,False,False,False,False,False,False,False,False,False,False,False
167,False,False,False,False,False,False,False,False,False,False,False
168,False,False,False,False,False,False,False,False,False,False,False
169,False,False,False,False,False,False,False,False,False,False,False
170,False,False,False,False,False,False,False,False,False,False,False
171,False,False,False,False,False,False,False,False,False,False,False
172,False,False,False,False,False,False,False,False,False,False,False
173,False,False,False,False,False,False,False,False,False,False,False
174,False,False,False,False,False,False,False,False,False,False,False
175,False,False,False,False,False,False,False,False,False,False,False
176,False,False,False,False,False,False,False,False,False,False,False
177,False,False,False,False,False,False,False,False,False,False,False
178,False,False,False,False,False,False,False,False,False,False,False
179,False,False,False,False,False,False,False,False,False,False,False
180,False,False,False,False,False,False,False,False,False,False,False
181,False,False,False,False,False,False,False,False,False,False,False
182,False,False,False,False,False,False,False,False,False,False,False
183,False,False,False,False,False,False,False,False,False,False,False
184,False,False,False,False,False,False,False,False,False,False,False
185,False,False,False,False,False,False,False,False,False,False,False
186,False,False,False,False,False,False,False,False,False,False,False
187,False,False,False,False,False,False,False,False,False,False,False
188,False,False,False,False,False,False,False,False,False,False,False
189,False,False,False,False,False,False,False,False,False,False,False
190,False,False,False,False,False,False,False,False,False,False,False
191,False,False,False,False,False,False,False,False,False,False,False
192,False,False,False,False,False,False,False,False,False,False,False
193,False,False,False,False,False,False,False,False,False,False,False
194,False,False,False,False,False,False,False,False,False,False,False
195,False,False,False,False,False,False,False,False,False,False,False
196,False,False,False,False,False,False,False,False,False,False,False
197,False,False,False,False,False,False,False,False,False,False,False
198,False,False,False,False,False,False,False,False,False,False,False
199,False,False,False,False,False,False,False,False,False,False,False
200,False,False,False,False,False,False,False,False,False,False,False
201,False,False,False,False,False,False,False,False,False,False,False
202,False,False,False,False,False,False,False,False,False,False,False
203,False,False,False,False,False,False,False,False,False,False,False
204,False,False,False,False,False,False,False,False,False,False,False
205,False,False,False,False,False,False,False,False,False,False,False
206,False,False,False,False,False,False,False,False,False,False,False
207,False,False,False,False,False,False,False,False,False,False,False
208,False,False,False,False,False,False,False,False,False,False,False
209,False,False,False,False,False,False,False,False,False,False,False
210,False,False,False,False,False,False,False,False,False,False,False
211,False,False,False,False,False,False,False,False,False,False,False
212,False,False,False,False,False,False,False,False,False,False,False
213,False,False,False,False,False,False,False,False,False,False,False
214,False,False,False,False,False,False,False,False,False,False,False
215,False,False,False,False,False,False,False,False,False,False,False
216,False,False,False,False,False,False,False,False,False,False,False
217,False,False,False,False,False,False,False,False,False,False,False
218,False,False,False,False,False,False,False,False,False,False,False
219,False,False,False,False,False,False,False,False,False,False,False
220,False,False,False,False,False,False,False,False,False,False,False
221,False,False,False,False,False,False,False,False,False,False,False
222,False,False,False,False,False,False,False,False,False,False,False
223,False,False,False,False,False,False,False,False,False,False,False
224,False,False,False,False,False,False,False,False,False,False,False
225,False,False,False,False,False,False,False,False,False,False,False
226,False,False,False,False,False,False,False,False,False,False,False
227,False,False,False,False,False,False,False,False,False,False,False
228,False,False,False,False,False,False,False,False,False,False,False
229,False,False,False,False,False,False,False,False,False,False,False
230,False,False,False,False,False,False,False,False,False,False,False
231,False,False,False,False,False,False,False,False,False,False,False
232,False,False,False,False,False,False,False,False,False,False,False
233,False,False,False,False,False,False,False,False,False,False,False
234,False,False,False,False,False,False,False,False,False,False,False
235,False,False,False,False,False,False,False,False,False,False,False
236,False,False,False,False,False,False,False,False,False,False,False
237,False,False,False,False,False,False,False,False,False,False,False
238,False,False,False,False,False,False,False,False,False,False,False
239,False,False,False,False,False,False,False,False,False,False,False
240,False,False,False,False,False,False,False,False,False,False,False
241,False,False,False,False,False,False,False,False,False,False,False

In [7]:
df.isnull().sum()

customer_id           0
age                   1
monthly_income_ghs    1
monthly_visits        0
annual_spend_ghs      0
segment               0
region                0
channel               0
satisfaction_score    0
returned_item         0
signup_date           0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(2)

In [ ]:
df_clean = df.copy()
df_clean['segment'] =
df_clean['segment']